### ISSUE TITLE
`db/seeds/main.go` tries to import `

### ISSUE THREAD

**Issue by sunwukonga** [qor/qor-example#52]

**Comment by roscopecoltran** [comment]
It is a true mess qo-example, only fixes for me too ^^

Would be awesome for the qor team to fix them and to provide a separate repo with docker-compose + a stable version of QOR to bootstrap quickly...

Richard

**Comment by roboto-cloud** [comment]
@roscopecoltran would be wonderful if @jinzhu team's  provide a docker-compose.yml..
here my issue about that: https://github.com/qor/qor-example/issues/117

but I think we need a Dockerfile + docker-compose.yml

Dockerfile:
```
FROM golang
RUN go get -u github.com/qor/qor-example
VOLUME /go/src
EXPOSE 9000
CMD go run $GOPATH/src/github.com/qor/qor-example/main.go
```

docker-compose.yml
```
version: "3"

services:
  web:
    container_name: web
    image: robotocloud/qor
    restart: always
    ports:
      - "9800:9800"
    links:
      - db:mysql
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - "MYSQL_DATABASE=qor_example"
```
